version: '3'
services:
    mysql:
        ports:
            - "3306:3306"
    php:
        ports:
            - "8000:8000"
    mailer:
        image: schickling/mailcatcher
        ports:
            - "1025"
            - "1080"
